[project]
name = "05-qdrant"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "fastapi-cli>=0.0.20",
    "langchain>=1.2.3",
    "langchain-mistralai>=1.1.1",
    "langchain-qdrant>=1.1.0",
    "pandas>=2.3.3",
    "qdrant-client>=1.16.2",
]
